package com.osh.chatting_bar_android.data_model;

public enum Categories {
    PHOTHOGRPAGHY, VOLUNTEERING, COSMETIC, FITNESS, OUTDOOR, HOME,
    DECO, DANCE, HISTORY, CARS, MOTORCYCLE, SPORT, DRAMA, MOVIE,
    STUDY, GAME, ART, MUSIC, BOOK, HEALTH, CODING, FOOD, COOKING,
    KPOP, FASHION, WORK, TRAVEL, KIDS
}
